#!/bin/bash

echo "cleaning system..."

#clean apt cache 
sudo apt autoremove 
sudo apt clean

# remove old systemctl journals
sudo journalctl --vacuum-time=3d



# Removes old revisions of snaps
# CLOSE ALL SNAPS BEFORE RUNNING THIS
set -eu
snap list --all | awk '/disabled/{print $1, $3}' |
    while read snapname revision; do
        sudo snap remove "$snapname" --revision="$revision"
    done

# remove thumbnail cache
sudo rm -rf ~/.cache/thumbnails/*


