#!/bin/bash

# clean snaps
clean_snap() {
  set -eu

  snap list --all | awk '/disabled/{print $1, $3}' |

      while read snapname revision; do

          sudo snap remove "$snapname" --revision="$revision"

      done
}


echo "cleaning system..."

#clean apt cache 
sudo apt autoremove 
sudo apt clean

# remove old systemctl journals
sudo journalctl --vacuum-time=3d

# remove thumbnail cache
sudo rm -rf ~/.cache/thumbnails/*

clean_snap
