#!/usr/bin/env -S uv run --script

import argparse
from tempfile import NamedTemporaryFile
import subprocess
import re
import sys

# edit this template for fine tuning
template = """\
1 # select type:
1 # MO
5 # select output format:
7 # cube
4 # select resolution
{grid} # ngrid
2 # select orbital number
{index} # orbital index
10 # create file
11 # quit program"""


def call_orca_plot(orb_idx, gbw, grid):
    "call orca_plot for orbitals orb_idx with operator spin on file gbw with grid"
    with NamedTemporaryFile(mode="w+") as f:  # only write temporary file
        content = template.format(grid=grid, index=orb_idx)
        f.write(content)

        f.seek(0)  # reset file pointer for reading
        subprocess.run(["orca_plot", gbw, "-i"], stdin=f, stdout=subprocess.DEVNULL)
        print(
            "INFO: Plotted orbital {} from {} using grid {}".format(
                orb_idx, gbw, grid
            )
        )


def expand_range(inp_str):
    inp_split = inp_str.split("-")
    int_list = list(range(int(inp_split[0]), int(inp_split[1]) + 1))
    str_list = [str(i) for i in int_list]
    return str_list


def convert_list(inp_str):
    inp_split = inp_str.split(",")
    res_list = []

    for i in inp_split:
        if "-" in i:
            res_list.extend(expand_range(i))
        else:
            res_list.append(i)

    return res_list


def run():
    parser = argparse.ArgumentParser(description="create cube from gbw")
    parser.add_argument("orca_gbw", metavar="ORCA_GBW", help="ORCA gbw file")
    parser.add_argument(
        "-g", "--grid", metavar="N", default=60, help="number of grid points"
    )
    parser.add_argument(
    "--index", 
    nargs='+', 
    type=str,
    help="A list of MO's to plot (space-separated)"
)

    args = parser.parse_args()

    grid = args.grid
    gbw = args.orca_gbw

    for i in args.index:
        call_orca_plot(orb_idx=i, gbw=gbw, grid=grid)



if __name__ == "__main__":
    run()
