#!/usr/bin/bash

# This script is used at the end of work, it syncs all work with google drive  
# It also checks for running jobs in both the local machine and remote clusters
# if nothing of the local machine is required (no jobs running) it shuts down

# back up in google drive
gdrivefolders=("$HOME/Chem" "$HOME/Documents" "$HOME/physics" )
gitfolders=("$HOME/Repos/chemgui" "$HOME/Repos/chemgui-openbabel" "$HOME/Chem/doutorado/projects/datasets" "$HOME/Chem/doutorado/projects/janus-crown" "$HOME/Chem/doutorado/projects/perichromic-probes" "$HOME/scripts")

# create log files
touch $HOME/tmp.log
touch $HOME/tmp.gdrive.log

# log=$HOME/tmp.log
# drivelog=$HOME/gdrive.tmp.log

# sync with back up in google drive
echo "====================================" >> $HOME/tmp.log 
echo "            GoodNight :)" >> $HOME/tmp.log 
echo "====================================" >> $HOME/tmp.log 
echo  >> $HOME/tmp.log 
echo "Syncing gdrive..."  
echo "Gdrive:" >> $HOME/tmp.log

# sync google drive
for i in "${gdrivefolders[@]}"
do 
    cd $i 
    gdrive push > $HOME/tmp.gdrive.log 2>&1 
    echo "Checking folder $i " >> $HOME/tmp.log       
    echo "New files pushed:" >> $HOME/tmp.log       
    cat $HOME/tmp.gdrive.log| grep "new" | awk '{print $5 $6}' >> $HOME/tmp.log       
    echo "Files replaced:" >> $HOME/tmp.log       
    cat $HOME/tmp.gdrive.log| grep "replaced existing" | awk '{print $5 $6 $7 $8 $9}' >> $HOME/tmp.log       
    echo  >> $HOME/tmp.log       
done 

# sync taskwarrior 
task sync > /dev/null  2>&1 

# for every git repositary, check if it has files not staged/commited
echo "Syncing git folders"

for j in "${gitfolders[@]}"
do 
    echo "Checking $j" >> $HOME/tmp.log
    cd $j 
    # no added files
    echo "       Files unstaged:" >> $HOME/tmp.log 
    git diff --exit-code | grep '^diff' | awk '{print $3}' >> $HOME/tmp.log

    # no committed files 
    echo "       Files uncomitted:" >> $HOME/tmp.log 
    git diff --cached --exit-code | grep '^diff' | awk '{print $3}' >> $HOME/tmp.log


    # commited but not pushed 
    echo "       Commits not pushed to origin :" >> $HOME/tmp.log 
    head=`cat .git/HEAD | awk '{print $2}'`
    if [[ $head == "refs/heads/master" ]]; then
        git log origin/master..master | awk '{print $7}' >> $HOME/tmp.log 
    elif [[ $head == "refs/heads/main" ]]; then
        git log origin/main..main | awk '{print $7}' >> $HOME/tmp.log 
    else
        echo "Not on main/master branch... check $j directory" >> $HOME/tmp.log
    fi
    echo >> $HOME/tmp.log
    # no untracked files (do i need this?)

done 

# check cluster for completed jobs
echo "     Checking for completed jobs" >> $HOME/tmp.log

# print a quick log with the summary of the syncs
cat $HOME/tmp.log
rm $HOME/tmp.log $HOME/tmp.gdrive.log




