#!/home/vport/projects/scripts/.venv/bin/python
import matplotlib.pyplot as plt
import sys
import numpy as np
from scipy.interpolate import make_interp_spline

def main():
    file = sys.argv[1]
    with open(file, "r") as f:
        lines = f.readlines()

    start = 0
    end = 0

    for i in range(0, len(lines)):
        if "IRC PATH SUMMARY" in lines[i]:
            start = i + 5
        if "SUGGESTED CITATIONS FOR THIS RUN" in lines[i]:
            end = i - 3
        if "Timings for individual modules" in lines[i] and end == 0:
            end = i - 2            

    if start == 0 or end == 0:
        print("The log provided did not have an irc path summary")
        sys.exit()


    data = lines[start:end]

    y = []
    
    counter = 0
    ts = 0
    for line in data:
        if "TS" in line:
            ts = counter
        y.append(float(line.strip().split()[2]))
        counter += 1

    y = [j - y[0] for j in y]

    x = range(1,len(y) + 1)

    xy_spline = make_interp_spline(x,y)
    xsmooth = np.linspace(min(x), max(x), 500)
    ysmooth = xy_spline(xsmooth)
    
    plt.plot(xsmooth, ysmooth, "-.", color="blue")
    plt.plot(x,y, 'o', color="black")
    plt.plot(x[ts], y[ts], 'o', color="red")
    plt.xlabel("Distance (Bohr)")
    plt.ylabel("Energy(kcal mol-1)")
    plt.show()

if __name__ == "__main__":
    main()
