#!/bin/bash

# Default user
DEFAULT_USER=${DEFAULT_USER:-"vport@ufsc"}

# Initialize variables
USER="$DEFAULT_USER"
ALL_USERS=false
JOB_STATUS=""
FIELDS=()

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    -u|--user)
      USER="$2"
      shift # past argument
      shift # past value
      ;;
    -a|--all)
      ALL_USERS=true
      shift # past argument
      ;;
    -s|--status)
      JOB_STATUS="$2"
      shift # past argument
      shift # past value
      ;;
    -f|--field)
      FIELDS+=("$2")
      shift # past argument
      shift # past value
      ;;
    *)
      shift # past unrecognized argument
      ;;
  esac
done

# Create jq filter string
JQ_FILTER=".jobs[]"
if [ "$ALL_USERS" = false ]; then
  JQ_FILTER="$JQ_FILTER | select(.owner == \"$USER\")"
fi

if [ -n "$JOB_STATUS" ]; then
  JQ_FILTER="$JQ_FILTER | select(.status == \"$JOB_STATUS\")"
fi

# If no fields are specified, output the whole JSON structure
if [ ${#FIELDS[@]} -eq 0 ]; then
  JQ_FILTER="$JQ_FILTER"
else
  JQ_FILTER="$JQ_FILTER | {$(printf "%s," "${FIELDS[@]}" | sed 's/,$//')}"
fi

# Process JSON from stdin with jq
jq "$JQ_FILTER"
