#!/usr/bin/bash

#!/usr/bin/bash
CURRENT_DIR=`pwd`'/'

CLUSTER=$1
FILE=$2

if [[ "$CLUSTER" == "newton" ]] ; then
  REMOTE=$NEWTON_PROJECTS
elif [[ "$CLUSTER" == "jupiter" ]] ; then
  REMOTE=$JUPITER_PROJECTS
elif [[ "$CLUSTER" == "pipeline" ]] ; then
  REMOTE=$LOCAL_PROJECTS
else
  echo "ERROR: First argument must be 'newton', 'pipeline' or 'jupiter'"
  exit
fi

if [[ "$CURRENT_DIR" == "$LOCAL_PROJECTS"* ]] ; then
  LEN_LOCAL=${#LOCAL_PROJECTS}
  LEN_CURRENT=${#CURRENT_DIR}
  TARGET=$REMOTE${CURRENT_DIR:$LEN_LOCAL:$LEN_CURRENT}
else 
  echo "Current dir is NOT a $CLUSTER subfolder. Quitting."
  exit
fi

ssh $CLUSTER "cd $TARGET && tail -f $FILE"

